name: Deploy kdt
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to the remote server using SSH
      - name: SSH Login and Execute Commands
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }} # If you use a password (or use a private key)
          script: |
            cd /home/
            sudo ls