name: Deploy kdt
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Log in to the remote server using SSH
      - name: SSH Login and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }} # If you use a password (or use a private key)
          port: 22
          script: |
            cd /home/
            sudo ls